FetchContent_Declare(
    stb
    GIT_REPOSITORY https://github.com/nothings/stb.git
    GIT_TAG        master
)
FetchContent_MakeAvailable(stb)
FetchContent_GetProperties(stb)

file(GLOB_RECURSE SOURCE_DIR "src/**.cpp" "src/**.hpp")
add_library(Strype STATIC ${SOURCE_DIR})

target_include_directories(Strype PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/src)
target_precompile_headers(Strype PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/src/stypch.hpp)

target_include_directories(Strype PUBLIC ${stb_SOURCE_DIR})
target_link_libraries(Strype PUBLIC
    agi agi_imgui ImGuizmo
    miniaudio freetype
    spdlog::spdlog
    yaml-cpp::yaml-cpp
    magic_enum::magic_enum
    Coral
)

target_compile_definitions(Strype PUBLIC
    $<$<PLATFORM_ID:Windows>:STY_WINDOWS>
    $<$<PLATFORM_ID:Linux>:STY_LINUX>
    $<$<PLATFORM_ID:Darwin>:STY_MACOSX>

    $<$<CONFIG:Debug>:STY_DEBUG>
    $<$<CONFIG:Release>:STY_RELEASE>
    $<$<CONFIG:RelWithDebInfo>:STY_RELEASE>
    $<$<CONFIG:MinSizeRel>:STY_DIST>
    YAML_CPP_STATIC_DEFINE
    
    STY_VERSION="${PROJECT_VERSION}"
)

# Download scripting binaries
file(DOWNLOAD
    "https://github.com/JackJackStudios/Strype-ScriptCore/releases/download/latest/Coral.Managed.dll"
    "${CMAKE_CURRENT_SOURCE_DIR}/master/DotNet/Coral.Managed.dll"
    STATUS status)

file(DOWNLOAD
    "https://github.com/JackJackStudios/Strype-ScriptCore/releases/download/latest/Strype-ScriptCore.dll"
    "${CMAKE_CURRENT_SOURCE_DIR}/master/DotNet/Strype-ScriptCore.dll"
    STATUS status)

# Pack shader folder into a .embed
set(EMBED_SRC "${CMAKE_CURRENT_SOURCE_DIR}/master/**.glsl")
set(EMBED_OUT "${CMAKE_CURRENT_SOURCE_DIR}/baseshaders.embed")

file(WRITE "${EMBED_OUT}" "// Auto-generated shader embed file\n") 

file(GLOB_RECURSE FILES ${EMBED_SRC})

foreach(FILE ${FILES})
    if (NOT IS_DIRECTORY "${FILE}")
        get_filename_component(NAME "${FILE}" NAME_WE)
        file(READ "${FILE}" CONTENTS)

        string(REPLACE "\\" "\\\\" CONTENTS "${CONTENTS}")
        string(REPLACE "\"" "\\\"" CONTENTS "${CONTENTS}")
        string(REPLACE "\n" "\\n\"\n\"" CONTENTS "${CONTENTS}")
        string(REPLACE "\r" "" CONTENTS "${CONTENTS}")

        file(APPEND "${EMBED_OUT}" "static const char ${NAME}_data[] =\n\"${CONTENTS}\";\n")
        file(APPEND "${EMBED_OUT}" "static const size_t ${NAME}_size = sizeof(${NAME}_data);\n\n")
    endif()
endforeach()
