#pragma once
#include "stypch.h"

#include <GLFW/glfw3.h>

#define STY_KEY_SPACE              GLFW_KEY_SPACE          
#define STY_KEY_APOSTROPHE         GLFW_KEY_APOSTROPHE     
#define STY_KEY_COMMA              GLFW_KEY_COMMA          
#define STY_KEY_MINUS              GLFW_KEY_MINUS          
#define STY_KEY_PERIOD             GLFW_KEY_PERIOD         
#define STY_KEY_SLASH              GLFW_KEY_SLASH          
#define STY_KEY_0                  GLFW_KEY_0              
#define STY_KEY_1                  GLFW_KEY_1              
#define STY_KEY_2                  GLFW_KEY_2              
#define STY_KEY_3                  GLFW_KEY_3              
#define STY_KEY_4                  GLFW_KEY_4              
#define STY_KEY_5                  GLFW_KEY_5              
#define STY_KEY_6                  GLFW_KEY_6              
#define STY_KEY_7                  GLFW_KEY_7              
#define STY_KEY_8                  GLFW_KEY_8              
#define STY_KEY_9                  GLFW_KEY_9              
#define STY_KEY_SEMICOLON          GLFW_KEY_SEMICOLON      
#define STY_KEY_EQUAL              GLFW_KEY_EQUAL          
#define STY_KEY_A                  GLFW_KEY_A              
#define STY_KEY_B                  GLFW_KEY_B              
#define STY_KEY_C                  GLFW_KEY_C              
#define STY_KEY_D                  GLFW_KEY_D              
#define STY_KEY_E                  GLFW_KEY_E              
#define STY_KEY_F                  GLFW_KEY_F              
#define STY_KEY_G                  GLFW_KEY_G              
#define STY_KEY_H                  GLFW_KEY_H              
#define STY_KEY_I                  GLFW_KEY_I              
#define STY_KEY_J                  GLFW_KEY_J              
#define STY_KEY_K                  GLFW_KEY_K              
#define STY_KEY_L                  GLFW_KEY_L              
#define STY_KEY_M                  GLFW_KEY_M              
#define STY_KEY_N                  GLFW_KEY_N              
#define STY_KEY_O                  GLFW_KEY_O              
#define STY_KEY_P                  GLFW_KEY_P              
#define STY_KEY_Q                  GLFW_KEY_Q              
#define STY_KEY_R                  GLFW_KEY_R              
#define STY_KEY_S                  GLFW_KEY_S              
#define STY_KEY_T                  GLFW_KEY_T              
#define STY_KEY_U                  GLFW_KEY_U              
#define STY_KEY_V                  GLFW_KEY_V              
#define STY_KEY_W                  GLFW_KEY_W              
#define STY_KEY_X                  GLFW_KEY_X              
#define STY_KEY_Y                  GLFW_KEY_Y              
#define STY_KEY_Z                  GLFW_KEY_Z              
#define STY_KEY_LEFT_BRACKET       GLFW_KEY_LEFT_BRACKET   
#define STY_KEY_BACKSLASH          GLFW_KEY_BACKSLASH      
#define STY_KEY_RIGHT_BRACKET      GLFW_KEY_RIGHT_BRACKET  
#define STY_KEY_GRAVE_ACCENT       GLFW_KEY_GRAVE_ACCENT   
#define STY_KEY_WORLD_1            GLFW_KEY_WORLD_1        
#define STY_KEY_WORLD_2            GLFW_KEY_WORLD_2        

#define STY_KEY_ESCAPE             GLFW_KEY_ESCAPE         
#define STY_KEY_ENTER              GLFW_KEY_ENTER          
#define STY_KEY_TAB                GLFW_KEY_TAB            
#define STY_KEY_BACKSPACE          GLFW_KEY_BACKSPACE      
#define STY_KEY_INSERT             GLFW_KEY_INSERT         
#define STY_KEY_DELETE             GLFW_KEY_DELETE         
#define STY_KEY_RIGHT              GLFW_KEY_RIGHT          
#define STY_KEY_LEFT               GLFW_KEY_LEFT           
#define STY_KEY_DOWN               GLFW_KEY_DOWN           
#define STY_KEY_UP                 GLFW_KEY_UP             
#define STY_KEY_PAGE_UP            GLFW_KEY_PAGE_UP        
#define STY_KEY_PAGE_DOWN          GLFW_KEY_PAGE_DOWN      
#define STY_KEY_HOME               GLFW_KEY_HOME           
#define STY_KEY_END                GLFW_KEY_END            
#define STY_KEY_CAPS_LOCK          GLFW_KEY_CAPS_LOCK      
#define STY_KEY_SCROLL_LOCK        GLFW_KEY_SCROLL_LOCK    
#define STY_KEY_NUM_LOCK           GLFW_KEY_NUM_LOCK       
#define STY_KEY_PRINT_SCREEN       GLFW_KEY_PRINT_SCREEN   
#define STY_KEY_PAUSE              GLFW_KEY_PAUSE          
#define STY_KEY_F1                 GLFW_KEY_F1             
#define STY_KEY_F2                 GLFW_KEY_F2             
#define STY_KEY_F3                 GLFW_KEY_F3             
#define STY_KEY_F4                 GLFW_KEY_F4             
#define STY_KEY_F5                 GLFW_KEY_F5             
#define STY_KEY_F6                 GLFW_KEY_F6             
#define STY_KEY_F7                 GLFW_KEY_F7             
#define STY_KEY_F8                 GLFW_KEY_F8             
#define STY_KEY_F9                 GLFW_KEY_F9             
#define STY_KEY_F10                GLFW_KEY_F10            
#define STY_KEY_F11                GLFW_KEY_F11            
#define STY_KEY_F12                GLFW_KEY_F12            
#define STY_KEY_F13                GLFW_KEY_F13            
#define STY_KEY_F14                GLFW_KEY_F14            
#define STY_KEY_F15                GLFW_KEY_F15            
#define STY_KEY_F16                GLFW_KEY_F16            
#define STY_KEY_F17                GLFW_KEY_F17            
#define STY_KEY_F18                GLFW_KEY_F18            
#define STY_KEY_F19                GLFW_KEY_F19            
#define STY_KEY_F20                GLFW_KEY_F20            
#define STY_KEY_F21                GLFW_KEY_F21            
#define STY_KEY_F22                GLFW_KEY_F22            
#define STY_KEY_F23                GLFW_KEY_F23            
#define STY_KEY_F24                GLFW_KEY_F24            
#define STY_KEY_F25                GLFW_KEY_F25            
#define STY_KEY_KP_0               GLFW_KEY_KP_0           
#define STY_KEY_KP_1               GLFW_KEY_KP_1           
#define STY_KEY_KP_2               GLFW_KEY_KP_2           
#define STY_KEY_KP_3               GLFW_KEY_KP_3           
#define STY_KEY_KP_4               GLFW_KEY_KP_4           
#define STY_KEY_KP_5               GLFW_KEY_KP_5           
#define STY_KEY_KP_6               GLFW_KEY_KP_6           
#define STY_KEY_KP_7               GLFW_KEY_KP_7           
#define STY_KEY_KP_8               GLFW_KEY_KP_8           
#define STY_KEY_KP_9               GLFW_KEY_KP_9           
#define STY_KEY_KP_DECIMAL         GLFW_KEY_KP_DECIMAL     
#define STY_KEY_KP_DIVIDE          GLFW_KEY_KP_DIVIDE      
#define STY_KEY_KP_MULTIPLY        GLFW_KEY_KP_MULTIPLY    
#define STY_KEY_KP_SUBTRACT        GLFW_KEY_KP_SUBTRACT    
#define STY_KEY_KP_ADD             GLFW_KEY_KP_ADD         
#define STY_KEY_KP_ENTER           GLFW_KEY_KP_ENTER       
#define STY_KEY_KP_EQUAL           GLFW_KEY_KP_EQUAL       
#define STY_KEY_LEFT_SHIFT         GLFW_KEY_LEFT_SHIFT     
#define STY_KEY_LEFT_CONTROL       GLFW_KEY_LEFT_CONTROL   
#define STY_KEY_LEFT_ALT           GLFW_KEY_LEFT_ALT       
#define STY_KEY_LEFT_SUPER         GLFW_KEY_LEFT_SUPER     
#define STY_KEY_RIGHT_SHIFT        GLFW_KEY_RIGHT_SHIFT    
#define STY_KEY_RIGHT_CONTROL      GLFW_KEY_RIGHT_CONTROL  
#define STY_KEY_RIGHT_ALT          GLFW_KEY_RIGHT_ALT      
#define STY_KEY_RIGHT_SUPER        GLFW_KEY_RIGHT_SUPER    
#define STY_KEY_MENU               GLFW_KEY_MENU           

#define STY_MOUSE_BUTTON_1         GLFW_MOUSE_BUTTON_1     
#define STY_MOUSE_BUTTON_2         GLFW_MOUSE_BUTTON_2     
#define STY_MOUSE_BUTTON_3         GLFW_MOUSE_BUTTON_3     
#define STY_MOUSE_BUTTON_4         GLFW_MOUSE_BUTTON_4     
#define STY_MOUSE_BUTTON_5         GLFW_MOUSE_BUTTON_5     
#define STY_MOUSE_BUTTON_6         GLFW_MOUSE_BUTTON_6     
#define STY_MOUSE_BUTTON_7         GLFW_MOUSE_BUTTON_7     
#define STY_MOUSE_BUTTON_8         GLFW_MOUSE_BUTTON_8     
#define STY_MOUSE_BUTTON_LAST      GLFW_MOUSE_BUTTON_LAST 
#define STY_MOUSE_BUTTON_LEFT      GLFW_MOUSE_BUTTON_LEFT 
#define STY_MOUSE_BUTTON_RIGHT     GLFW_MOUSE_BUTTON_RIGHT  
#define STY_MOUSE_BUTTON_MIDDLE    GLFW_MOUSE_BUTTON_MIDDLE